# Week1: Basic Data Analytics Using Numpy

## Basic Array Operations 

In [2]:
import numpy as np
arr=np.array([1,2,3,4,5])
print("Array", arr)

Array [1 2 3 4 5]


In [4]:
#Perform Arithmetic operation
add=arr+5
print("Add 5:",add)
mul=arr*2
print("Multiple by 2:", mul)

Add 5: [ 6  7  8  9 10]
Multiple by 2: [ 2  4  6  8 10]


## Calculate mean, median, standard deviation 

In [6]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("Mean:",np.mean(arr))
print("Median:",np.median(arr))
print("Standard Deviation:",np.std(arr))

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143


## Reshaping array 

In [7]:
arr=np.arange(1,13)
reshape_arr=arr.reshape(3,4)
print("Reshape array:\n",reshape_arr)

Reshape array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Array Indexing 

In [8]:
arr=np.array([10,20,30,40,50])
print("First Element:",arr[0])
print("Last Element:",arr[-1])
print("Slice (1 to 3):",arr[1:4])

First Element: 10
Last Element: 50
Slice (1 to 3): [20 30 40]


## Array Concatenation

In [9]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
concatenated=np.concatenate((arr1,arr2))
print("Concatenated Array:", concatenated)

Concatenated Array: [1 2 3 4 5 6]


## Boolean Indexing to filter array

In [10]:
arr=np.array([1,2,3,4,5])
filter_arr=arr[arr>2]
print("Filter array(Greater than 2):",filter_arr)

Filter array(Greater than 2): [3 4 5]


## Dot Product 

In [11]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
dot_product=np.dot(arr1,arr2)
print("Dot Product:",dot_product)

Dot Product: 32


## Linear Algebra Operations

In [13]:
matrix=np.array([[1,2],[3,4]])
determinant=np.linalg.det(matrix)
inverse=np.linalg.inv(matrix)
print("Determinate:",determinant)
print("Inverse:", inverse)

Determinate: -2.0000000000000004
Inverse: [[-2.   1. ]
 [ 1.5 -0.5]]
